from django.urls import path, re_path
from django.contrib.auth.views import LoginView, logout_then_login
from . import views

app_name = 'fisiocore'

urlpatterns = [
    path('', views.patients, name='patients'),
    path('patient/add', views.add_patient, name='add_patient'),
    path('patient/view/<int:patient_id>', views.view_patient, name='view_patient'),
    path('patient/edit/<int:patient_id>', views.edit_patient, name='edit_patient'),
    path('patient/delete/<int:patient_id>', views.delete_patient, name='delete_patient'),
    path('patient/viewconsents/<int:patient_id>', views.view_consents, name='view_consents'),
    path('patient/viewconsent/<int:consent_id>', views.view_consent, name='view_consent'),
    path('patient/addconsent/<int:patient_id>', views.add_consent, name='add_consent'),
    path('patient/revokeconsent/<int:consent_id>', views.revoke_consent, name='revoke_consent'),
    path('patient/examination/<int:patient_id>', views.examination, name='examination'),
    path('patient/examination/<int:patient_id>/<int:examination_id>', views.examination, name='examination'),
    path('patient/listimages/<int:patient_id>', views.imagelist, name='imagelist'),
    path('patient/listimages/<int:patient_id>/<int:image_id>', views.imagelist, name='imagelist'),
    path('patient/listdocuments/<int:patient_id>', views.document_list, name='documentlist'),
    path('patient/listdocuments/<int:patient_id>/<int:document_id>', views.document_list, name='documentlist'),
    path('patient/listsessions/<int:patient_id>', views.session_list, name='sessionlist'),
    path('patient/listsessions/<int:patient_id>/<int:session_id>', views.session_list, name='sessionlist'),
    path('patient/addanamnesis/<int:patient_id>', views.add_examination, name='add_examination'),
    path('patient/editanamnesis/<int:examination_id>', views.edit_examination, name='edit_examination'),
    path('patient/deleteanamnesis/<int:examination_id>', views.delete_examination, name='delete_examination'),
    path('patient/addimages/<int:examination_id>', views.add_images, name='add_images'),
    path('patient/viewimage/<int:image_id>', views.view_medical_image, name='view_medical_image'),
    path('patient/editimage/<int:image_id>', views.edit_medical_image, name='edit_medical_image'),
    path('patient/deleteimage/<int:image_id>', views.delete_medical_image, name='delete_medical_image'),
    path('patient/adddocument/<int:examination_id>', views.add_document, name='add_document'),
    path('patient/viewdocument/<int:document_id>', views.view_document, name='view_document'),
    path('patient/editdocument/<int:document_id>', views.edit_document, name='edit_document'),
    path('patient/deletedocument/<int:document_id>', views.delete_document, name='delete_document'),
    path('patient/sessions/<int:patient_id>', views.view_sessions, name='view_sessions'),
    path('patient/sessions/<int:patient_id>/<int:session_id>', views.view_sessions, name='view_sessions'),
    path('patient/treatmentplans/<int:patient_id>/<int:treatmentplan_id>', views.view_treatmentplans, name='view_treatmentplans'),
    path('patient/treatmentplans/<int:patient_id>', views.view_treatmentplans, name='view_treatmentplans'),
    path('patient/addtreatmentplan/<int:patient_id>', views.add_treatmentplan, name='add_treatmentplan'),
    path('user/stats', views.stats, name='stats'),
    path('user/profile', views.userprofile, name='userprofile'),
    path('consents/list', views.view_consent_documents, name='view_consent_documents'),
    path('consents/view/<int:document_id>', views.view_consent_document, name='view_consent_document'),
    path('consents/edit/<int:document_id>', views.edit_consent_document, name='edit_consent_document'),
    path('consents/delete/<int:document_id>', views.delete_consent_document, name='delete_consent_document'),
    path('consents/print/<int:patient_id>/<int:document_id>', views.print_consent_document, name='print_consent_document'),
    path('consents/add', views.add_consent_document, name='add_consent_document'),
    path('templates/exploration/list', views.list_exploration_templates, name="list_exploration_templates"),
    path('templates/exploration/view/<int:tmpl_id>', views.view_exploration_template, name="view_exploration_template"),
    path('templates/exploration/add', views.add_exploration_template, name='add_exploration_template'),
    path('templates/exploration/edit/<int:tmpl_id>', views.edit_exploration_template, name="edit_exploration_template"),
    path('templates/exploration/delete/<int:tmpl_id>', views.delete_exploration_template, name="delete_exploration_template"),
    path('templates/exploration/select/<int:patient_id>', views.select_exploration_template, name="select_exploration_template"),
    path('calendar', views.view_calendar, name='calendar'),
    path('calendar/month', views.view_calendar, name='calendar'),
    path('calendar/month/<int:year>/<int:month>', views.view_calendar, name='calendar'),
    path('calendar/day/<int:year>/<int:month>/<int:day>', views.view_calendar_day, name='calendar_day'),
    path('calendar/addsession', views.add_session, name='add_session'),
    path('calendar/editsession/<int:session_id>', views.edit_session, name='edit_session'),
    path('calendar/deletesession/<int:session_id>', views.delete_session, name='delete_session'),
    path('tools/import', views.import_file, name="import"),
    path('tools/export', views.export_file, name="export"),
    path('login', LoginView.as_view(template_name = "fisiocore/login.html"), name='login'),
    path('logout', logout_then_login, name='logout'),
    re_path('^media/medical_images/\w+', views.medical_image, name='medical_image'),
    re_path('^media/clinical_documents/\w+', views.document, name='clinical_document')
]
