# Generated by Django 4.1.2 on 2022-10-25 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('second_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('post_code', models.CharField(max_length=10, verbose_name='Post code')),
                ('street', models.CharField(max_length=10, verbose_name='Street')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Last update')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('second_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('post_code', models.CharField(max_length=10, verbose_name='Post code')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('id_card_number', models.CharField(max_length=20, verbose_name='Id card')),
                ('ss_number', models.CharField(max_length=20, verbose_name='Social security number')),
                ('ss_country', models.CharField(max_length=2, verbose_name='Social security country')),
                ('ss_issue_date', models.DateField(verbose_name='Social security date of issue')),
                ('ss_expiry_date', models.DateField(verbose_name='Social security expiry date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('second_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('post_code', models.CharField(max_length=10, verbose_name='Post code')),
                ('street', models.CharField(max_length=10, verbose_name='Street')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Last update')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='Province')),
                ('post_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal code')),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax number')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('user', models.OneToOneField(help_text='The login user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentPlanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Last update')),
                ('name', models.CharField(help_text='Descriptive name for the treatment plan.', max_length=50, verbose_name='Name')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Overal price of the whole treatment plan.', max_digits=8, null=True)),
                ('session_count', models.PositiveSmallIntegerField(default=1)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisiocore.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Last update')),
                ('name', models.CharField(help_text='Descriptive name for the treatment plan.', max_length=50, verbose_name='Name')),
                ('description', models.TextField(help_text='Detailed description of the treatment plan. Supports Markdown')),
                ('number_of_sessions', models.SmallIntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Overal price of the whole treatment plan.', max_digits=8, null=True)),
                ('active', models.BooleanField(verbose_name='Active')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fisiocore.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisiocore.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('session_number', models.PositiveSmallIntegerField(default=1)),
                ('completed', models.BooleanField()),
                ('remarks', models.TextField(help_text="Anything remarkable such as patient's progress")),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fisiocore.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisiocore.patient')),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisiocore.treatmentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisiocore.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Last update')),
                ('report', models.TextField(verbose_name='Patient report')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisiocore.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisiocore.patient'),
        ),
        migrations.CreateModel(
            name='InformedConsentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Last update')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InformedConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Last update')),
                ('signed_consent', models.ImageField(upload_to='signed_consent/', verbose_name='Informed consent')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisiocore.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Last update')),
                ('anamnesis', models.TextField(help_text='Any health related information given by the patient.', verbose_name='Anamnesis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisiocore.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
