# Generated by Django 4.1.2 on 2022-10-25 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fisiocore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
