# Generated by Django 4.1.2 on 2022-10-25 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisiocore', '0002_remove_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='invoice',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='fisiocore.invoice'),
        ),
        migrations.AlterField(
            model_name='session',
            name='remarks',
            field=models.TextField(blank=True, help_text="Anything remarkable such as patient's progress", null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='treatment_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fisiocore.treatmentplan'),
        ),
    ]
