# Generated by Django 4.1.2 on 2022-10-25 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisiocore', '0003_alter_session_invoice_alter_session_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fisiocore.invoice'),
        ),
        migrations.AlterField(
            model_name='session',
            name='treatment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fisiocore.treatmentplan'),
        ),
    ]
