# Generated by Django 4.1.2 on 2022-10-26 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisiocore', '0004_alter_session_invoice_alter_session_treatment_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['date', 'start']},
        ),
        migrations.AlterField(
            model_name='informedconsent',
            name='signed_consent',
            field=models.FileField(upload_to='signed_consent/', verbose_name='Informed consent'),
        ),
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Last update')),
                ('image_type', models.CharField(choices=[('FOTO', 'Photography'), ('XRAY', 'X-Ray'), ('ECHO', 'Ultrasound'), ('TAC', 'CT scan'), ('RMN', 'Nuclear magnetic resonance'), ('UNKN', 'Unknown/other')], default='UNKN', max_length=4)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisiocore.patient')),
            ],
        ),
    ]
