# Generated by Django 4.1.2 on 2022-10-26 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisiocore', '0005_alter_session_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalimage',
            name='patient',
        ),
        migrations.AddField(
            model_name='medicalimage',
            name='anamnesis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fisiocore.anamnesis'),
            preserve_default=False,
        ),
    ]
